# Generated by Django 3.2.7 on 2021-10-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='age',
        ),
    ]
