# Generated by Django 3.2.6 on 2021-10-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='memders',
            new_name='members',
        ),
    ]
