# Generated by Django 3.2.8 on 2021-10-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
