# Generated by Django 3.2.8 on 2021-10-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_teal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teal',
            new_name='Team',
        ),
    ]
