# Generated by Django 3.2.8 on 2021-10-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_rename_teal_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
