# Generated by Django 3.2.7 on 2021-10-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='mombers',
            new_name='members',
        ),
    ]
