# Generated by Django 3.2.6 on 2021-10-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_rename_memders_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
