# Generated by Django 3.2.8 on 2021-10-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_hero_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
