# Generated by Django 3.2.7 on 2021-10-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_rename_mombers_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
