# Generated by Django 3.2.7 on 2021-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_team_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
        migrations.AddField(
            model_name='hero',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
